require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AssetListMastersController do

  # This should return the minimal set of attributes required to create a valid
  # AssetListMaster. As you add validations to AssetListMaster, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "type_id" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AssetListMastersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all asset_list_masters as @asset_list_masters" do
      asset_list_master = AssetListMaster.create! valid_attributes
      get :index, {}, valid_session
      assigns(:asset_list_masters).should eq([asset_list_master])
    end
  end

  describe "GET show" do
    it "assigns the requested asset_list_master as @asset_list_master" do
      asset_list_master = AssetListMaster.create! valid_attributes
      get :show, {:id => asset_list_master.to_param}, valid_session
      assigns(:asset_list_master).should eq(asset_list_master)
    end
  end

  describe "GET new" do
    it "assigns a new asset_list_master as @asset_list_master" do
      get :new, {}, valid_session
      assigns(:asset_list_master).should be_a_new(AssetListMaster)
    end
  end

  describe "GET edit" do
    it "assigns the requested asset_list_master as @asset_list_master" do
      asset_list_master = AssetListMaster.create! valid_attributes
      get :edit, {:id => asset_list_master.to_param}, valid_session
      assigns(:asset_list_master).should eq(asset_list_master)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AssetListMaster" do
        expect {
          post :create, {:asset_list_master => valid_attributes}, valid_session
        }.to change(AssetListMaster, :count).by(1)
      end

      it "assigns a newly created asset_list_master as @asset_list_master" do
        post :create, {:asset_list_master => valid_attributes}, valid_session
        assigns(:asset_list_master).should be_a(AssetListMaster)
        assigns(:asset_list_master).should be_persisted
      end

      it "redirects to the created asset_list_master" do
        post :create, {:asset_list_master => valid_attributes}, valid_session
        response.should redirect_to(AssetListMaster.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved asset_list_master as @asset_list_master" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssetListMaster.any_instance.stub(:save).and_return(false)
        post :create, {:asset_list_master => { "type_id" => "invalid value" }}, valid_session
        assigns(:asset_list_master).should be_a_new(AssetListMaster)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssetListMaster.any_instance.stub(:save).and_return(false)
        post :create, {:asset_list_master => { "type_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested asset_list_master" do
        asset_list_master = AssetListMaster.create! valid_attributes
        # Assuming there are no other asset_list_masters in the database, this
        # specifies that the AssetListMaster created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AssetListMaster.any_instance.should_receive(:update_attributes).with({ "type_id" => "" })
        put :update, {:id => asset_list_master.to_param, :asset_list_master => { "type_id" => "" }}, valid_session
      end

      it "assigns the requested asset_list_master as @asset_list_master" do
        asset_list_master = AssetListMaster.create! valid_attributes
        put :update, {:id => asset_list_master.to_param, :asset_list_master => valid_attributes}, valid_session
        assigns(:asset_list_master).should eq(asset_list_master)
      end

      it "redirects to the asset_list_master" do
        asset_list_master = AssetListMaster.create! valid_attributes
        put :update, {:id => asset_list_master.to_param, :asset_list_master => valid_attributes}, valid_session
        response.should redirect_to(asset_list_master)
      end
    end

    describe "with invalid params" do
      it "assigns the asset_list_master as @asset_list_master" do
        asset_list_master = AssetListMaster.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssetListMaster.any_instance.stub(:save).and_return(false)
        put :update, {:id => asset_list_master.to_param, :asset_list_master => { "type_id" => "invalid value" }}, valid_session
        assigns(:asset_list_master).should eq(asset_list_master)
      end

      it "re-renders the 'edit' template" do
        asset_list_master = AssetListMaster.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssetListMaster.any_instance.stub(:save).and_return(false)
        put :update, {:id => asset_list_master.to_param, :asset_list_master => { "type_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested asset_list_master" do
      asset_list_master = AssetListMaster.create! valid_attributes
      expect {
        delete :destroy, {:id => asset_list_master.to_param}, valid_session
      }.to change(AssetListMaster, :count).by(-1)
    end

    it "redirects to the asset_list_masters list" do
      asset_list_master = AssetListMaster.create! valid_attributes
      delete :destroy, {:id => asset_list_master.to_param}, valid_session
      response.should redirect_to(asset_list_masters_url)
    end
  end

end
