require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AssetListsController do

  # This should return the minimal set of attributes required to create a valid
  # AssetList. As you add validations to AssetList, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "item_id" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AssetListsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all asset_lists as @asset_lists" do
      asset_list = AssetList.create! valid_attributes
      get :index, {}, valid_session
      assigns(:asset_lists).should eq([asset_list])
    end
  end

  describe "GET show" do
    it "assigns the requested asset_list as @asset_list" do
      asset_list = AssetList.create! valid_attributes
      get :show, {:id => asset_list.to_param}, valid_session
      assigns(:asset_list).should eq(asset_list)
    end
  end

  describe "GET new" do
    it "assigns a new asset_list as @asset_list" do
      get :new, {}, valid_session
      assigns(:asset_list).should be_a_new(AssetList)
    end
  end

  describe "GET edit" do
    it "assigns the requested asset_list as @asset_list" do
      asset_list = AssetList.create! valid_attributes
      get :edit, {:id => asset_list.to_param}, valid_session
      assigns(:asset_list).should eq(asset_list)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AssetList" do
        expect {
          post :create, {:asset_list => valid_attributes}, valid_session
        }.to change(AssetList, :count).by(1)
      end

      it "assigns a newly created asset_list as @asset_list" do
        post :create, {:asset_list => valid_attributes}, valid_session
        assigns(:asset_list).should be_a(AssetList)
        assigns(:asset_list).should be_persisted
      end

      it "redirects to the created asset_list" do
        post :create, {:asset_list => valid_attributes}, valid_session
        response.should redirect_to(AssetList.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved asset_list as @asset_list" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssetList.any_instance.stub(:save).and_return(false)
        post :create, {:asset_list => { "item_id" => "invalid value" }}, valid_session
        assigns(:asset_list).should be_a_new(AssetList)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssetList.any_instance.stub(:save).and_return(false)
        post :create, {:asset_list => { "item_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested asset_list" do
        asset_list = AssetList.create! valid_attributes
        # Assuming there are no other asset_lists in the database, this
        # specifies that the AssetList created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AssetList.any_instance.should_receive(:update_attributes).with({ "item_id" => "" })
        put :update, {:id => asset_list.to_param, :asset_list => { "item_id" => "" }}, valid_session
      end

      it "assigns the requested asset_list as @asset_list" do
        asset_list = AssetList.create! valid_attributes
        put :update, {:id => asset_list.to_param, :asset_list => valid_attributes}, valid_session
        assigns(:asset_list).should eq(asset_list)
      end

      it "redirects to the asset_list" do
        asset_list = AssetList.create! valid_attributes
        put :update, {:id => asset_list.to_param, :asset_list => valid_attributes}, valid_session
        response.should redirect_to(asset_list)
      end
    end

    describe "with invalid params" do
      it "assigns the asset_list as @asset_list" do
        asset_list = AssetList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssetList.any_instance.stub(:save).and_return(false)
        put :update, {:id => asset_list.to_param, :asset_list => { "item_id" => "invalid value" }}, valid_session
        assigns(:asset_list).should eq(asset_list)
      end

      it "re-renders the 'edit' template" do
        asset_list = AssetList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssetList.any_instance.stub(:save).and_return(false)
        put :update, {:id => asset_list.to_param, :asset_list => { "item_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested asset_list" do
      asset_list = AssetList.create! valid_attributes
      expect {
        delete :destroy, {:id => asset_list.to_param}, valid_session
      }.to change(AssetList, :count).by(-1)
    end

    it "redirects to the asset_lists list" do
      asset_list = AssetList.create! valid_attributes
      delete :destroy, {:id => asset_list.to_param}, valid_session
      response.should redirect_to(asset_lists_url)
    end
  end

end
