require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProductSalesController do

  # This should return the minimal set of attributes required to create a valid
  # ProductSale. As you add validations to ProductSale, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "transaction_id" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProductSalesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all product_sales as @product_sales" do
      product_sale = ProductSale.create! valid_attributes
      get :index, {}, valid_session
      assigns(:product_sales).should eq([product_sale])
    end
  end

  describe "GET show" do
    it "assigns the requested product_sale as @product_sale" do
      product_sale = ProductSale.create! valid_attributes
      get :show, {:id => product_sale.to_param}, valid_session
      assigns(:product_sale).should eq(product_sale)
    end
  end

  describe "GET new" do
    it "assigns a new product_sale as @product_sale" do
      get :new, {}, valid_session
      assigns(:product_sale).should be_a_new(ProductSale)
    end
  end

  describe "GET edit" do
    it "assigns the requested product_sale as @product_sale" do
      product_sale = ProductSale.create! valid_attributes
      get :edit, {:id => product_sale.to_param}, valid_session
      assigns(:product_sale).should eq(product_sale)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProductSale" do
        expect {
          post :create, {:product_sale => valid_attributes}, valid_session
        }.to change(ProductSale, :count).by(1)
      end

      it "assigns a newly created product_sale as @product_sale" do
        post :create, {:product_sale => valid_attributes}, valid_session
        assigns(:product_sale).should be_a(ProductSale)
        assigns(:product_sale).should be_persisted
      end

      it "redirects to the created product_sale" do
        post :create, {:product_sale => valid_attributes}, valid_session
        response.should redirect_to(ProductSale.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved product_sale as @product_sale" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProductSale.any_instance.stub(:save).and_return(false)
        post :create, {:product_sale => { "transaction_id" => "invalid value" }}, valid_session
        assigns(:product_sale).should be_a_new(ProductSale)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProductSale.any_instance.stub(:save).and_return(false)
        post :create, {:product_sale => { "transaction_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested product_sale" do
        product_sale = ProductSale.create! valid_attributes
        # Assuming there are no other product_sales in the database, this
        # specifies that the ProductSale created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProductSale.any_instance.should_receive(:update_attributes).with({ "transaction_id" => "" })
        put :update, {:id => product_sale.to_param, :product_sale => { "transaction_id" => "" }}, valid_session
      end

      it "assigns the requested product_sale as @product_sale" do
        product_sale = ProductSale.create! valid_attributes
        put :update, {:id => product_sale.to_param, :product_sale => valid_attributes}, valid_session
        assigns(:product_sale).should eq(product_sale)
      end

      it "redirects to the product_sale" do
        product_sale = ProductSale.create! valid_attributes
        put :update, {:id => product_sale.to_param, :product_sale => valid_attributes}, valid_session
        response.should redirect_to(product_sale)
      end
    end

    describe "with invalid params" do
      it "assigns the product_sale as @product_sale" do
        product_sale = ProductSale.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProductSale.any_instance.stub(:save).and_return(false)
        put :update, {:id => product_sale.to_param, :product_sale => { "transaction_id" => "invalid value" }}, valid_session
        assigns(:product_sale).should eq(product_sale)
      end

      it "re-renders the 'edit' template" do
        product_sale = ProductSale.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProductSale.any_instance.stub(:save).and_return(false)
        put :update, {:id => product_sale.to_param, :product_sale => { "transaction_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested product_sale" do
      product_sale = ProductSale.create! valid_attributes
      expect {
        delete :destroy, {:id => product_sale.to_param}, valid_session
      }.to change(ProductSale, :count).by(-1)
    end

    it "redirects to the product_sales list" do
      product_sale = ProductSale.create! valid_attributes
      delete :destroy, {:id => product_sale.to_param}, valid_session
      response.should redirect_to(product_sales_url)
    end
  end

end
