require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StoringsController do

  # This should return the minimal set of attributes required to create a valid
  # Storing. As you add validations to Storing, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "type_id" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StoringsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all storings as @storings" do
      storing = Storing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:storings).should eq([storing])
    end
  end

  describe "GET show" do
    it "assigns the requested storing as @storing" do
      storing = Storing.create! valid_attributes
      get :show, {:id => storing.to_param}, valid_session
      assigns(:storing).should eq(storing)
    end
  end

  describe "GET new" do
    it "assigns a new storing as @storing" do
      get :new, {}, valid_session
      assigns(:storing).should be_a_new(Storing)
    end
  end

  describe "GET edit" do
    it "assigns the requested storing as @storing" do
      storing = Storing.create! valid_attributes
      get :edit, {:id => storing.to_param}, valid_session
      assigns(:storing).should eq(storing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Storing" do
        expect {
          post :create, {:storing => valid_attributes}, valid_session
        }.to change(Storing, :count).by(1)
      end

      it "assigns a newly created storing as @storing" do
        post :create, {:storing => valid_attributes}, valid_session
        assigns(:storing).should be_a(Storing)
        assigns(:storing).should be_persisted
      end

      it "redirects to the created storing" do
        post :create, {:storing => valid_attributes}, valid_session
        response.should redirect_to(Storing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved storing as @storing" do
        # Trigger the behavior that occurs when invalid params are submitted
        Storing.any_instance.stub(:save).and_return(false)
        post :create, {:storing => { "type_id" => "invalid value" }}, valid_session
        assigns(:storing).should be_a_new(Storing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Storing.any_instance.stub(:save).and_return(false)
        post :create, {:storing => { "type_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested storing" do
        storing = Storing.create! valid_attributes
        # Assuming there are no other storings in the database, this
        # specifies that the Storing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Storing.any_instance.should_receive(:update_attributes).with({ "type_id" => "" })
        put :update, {:id => storing.to_param, :storing => { "type_id" => "" }}, valid_session
      end

      it "assigns the requested storing as @storing" do
        storing = Storing.create! valid_attributes
        put :update, {:id => storing.to_param, :storing => valid_attributes}, valid_session
        assigns(:storing).should eq(storing)
      end

      it "redirects to the storing" do
        storing = Storing.create! valid_attributes
        put :update, {:id => storing.to_param, :storing => valid_attributes}, valid_session
        response.should redirect_to(storing)
      end
    end

    describe "with invalid params" do
      it "assigns the storing as @storing" do
        storing = Storing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Storing.any_instance.stub(:save).and_return(false)
        put :update, {:id => storing.to_param, :storing => { "type_id" => "invalid value" }}, valid_session
        assigns(:storing).should eq(storing)
      end

      it "re-renders the 'edit' template" do
        storing = Storing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Storing.any_instance.stub(:save).and_return(false)
        put :update, {:id => storing.to_param, :storing => { "type_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested storing" do
      storing = Storing.create! valid_attributes
      expect {
        delete :destroy, {:id => storing.to_param}, valid_session
      }.to change(Storing, :count).by(-1)
    end

    it "redirects to the storings list" do
      storing = Storing.create! valid_attributes
      delete :destroy, {:id => storing.to_param}, valid_session
      response.should redirect_to(storings_url)
    end
  end

end
